### ISSUE TITLE
The stream option in OpenAI API is not supported.

### ISSUE THREAD

**Issue by htnosm** [newrelic/nr-openai-observability#10]
## Description

When using the stream option in OpenAI API, an AttributeError occurs.
As a result, the execution results of the OpenAI API cannot be retrieved.

## Steps to Reproduce

Code example:
(Added the option to the examples in the README.md)

```
import os

import openai
from nr_openai_observability import monitor

monitor.initialization()

openai.api_key = os.getenv("OPENAI_API_KEY")
openai.Completion.create(
    model="text-davinci-003",
    prompt="What is Observability?",
    max_tokens=20,
    temperature=0,
    stream=True  # ADD
)
```

## Expected Behavior

The process is executed normally regardless of the presence or absence of the option.
Alternatively, if the option is not supported, it is expected that the nr-openai-observability processing will be skipped and the results of the OpenAI API processing will be returned.

## Relevant Logs / Console output

When using the stream option in OpenAI API, an AttributeError occurs.

```
Traceback (most recent call last):
  File "/tmp/nr-openai/app.py", line 12, in <module>
    result = openai.Completion.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/nr-openai/.venv.11/lib/python3.11/site-packages/nr_openai_observability/monitor.py", line 20, in _inner_patch
    raise ex
  File "/tmp/nr-openai/.venv.11/lib/python3.11/site-packages/nr_openai_observability/monitor.py", line 18, in _inner_patch
    return patched_fn(original_fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/nr-openai/.venv.11/lib/python3.11/site-packages/nr_openai_observability/monitor.py", line 137, in patcher_create
    for i, choice in enumerate(result.get("choices")):
                               ^^^^^^^^^^
AttributeError: 'generator' object has no attribute 'get'
```

## Your Environment

* nr-openai-observability 0.2.5
* openai 0.27.7

## Additional context

OpenAI API Reference

* [completions](https://platform.openai.com/docs/api-reference/completions/create#completions/create-stream)
* [chat completion](https://platform.openai.com/docs/api-reference/chat/create#chat/create-stream)

**Comment by ykriger-newrelic** [comment]
Fixed. I apologize for the delay. We are not yet supporting streaming, but we've made changes to prevent the flow from breaking.
